<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net6.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>disable</Nullable>
		<RootNamespace>NoXrayCMS2026</RootNamespace>
		<LangVersion>default</LangVersion>
		<IsPackable>false</IsPackable>
		<AssemblyVersion>1.0.0.0</AssemblyVersion>
		<FileVersion>1.0.0.0</FileVersion>
		<NeutralLanguage>en-US</NeutralLanguage>
		<AssemblyName>NoXrayCMS2026</AssemblyName>
		<LangVersion>latest</LangVersion>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>

	<ItemGroup>
		<Reference Include="Assembly-CSharp-firstpass">
			<HintPath>$(GamePath)/MelonLoader\Il2CppAssemblies\Assembly-CSharp-firstpass.dll</HintPath>
		</Reference>
		<Reference Include="Assembly-CSharp">
			<HintPath>$(GamePath)/MelonLoader\Il2CppAssemblies\Assembly-CSharp.dll</HintPath>
		</Reference>
		<Reference Include="Il2CppCoffee.SoftMaskForUGUI.Demo">
			<HintPath>$(GamePath)/MelonLoader\Il2CppAssemblies\Il2CppCoffee.SoftMaskForUGUI.Demo.dll</HintPath>
		</Reference>
		<Reference Include="Il2CppCoffee.SoftMaskForUGUI">
			<HintPath>$(GamePath)/MelonLoader\Il2CppAssemblies\Il2CppCoffee.SoftMaskForUGUI.dll</HintPath>
		</Reference>
		<Reference Include="Il2Cppcom.rlabrecque.steamworks.net">
			<HintPath>$(GamePath)/MelonLoader\Il2CppAssemblies\Il2Cppcom.rlabrecque.steamworks.net.dll</HintPath>
		</Reference>
		<Reference Include="Il2CppDynamicSoundController">
			<HintPath>$(GamePath)/MelonLoader\Il2CppAssemblies\Il2CppDynamicSoundController.dll</HintPath>
		</Reference>
		<Reference Include="Il2CppFusion.Addons.SimpleKCC">
			<HintPath>$(GamePath)/MelonLoader\Il2CppAssemblies\Il2CppFusion.Addons.SimpleKCC.dll</HintPath>
		</Reference>
		<Reference Include="Il2CppFusion.Common">
			<HintPath>$(GamePath)/MelonLoader\Il2CppAssemblies\Il2CppFusion.Common.dll</HintPath>
		</Reference>
		<Reference Include="Il2CppFusion.Log">
			<HintPath>$(GamePath)/MelonLoader\Il2CppAssemblies\Il2CppFusion.Log.dll</HintPath>
		</Reference>
		<Reference Include="Il2CppFusion.Realtime">
			<HintPath>$(GamePath)/MelonLoader\Il2CppAssemblies\Il2CppFusion.Realtime.dll</HintPath>
		</Reference>
		<Reference Include="Il2CppFusion.Runtime">
			<HintPath>$(GamePath)/MelonLoader\Il2CppAssemblies\Il2CppFusion.Runtime.dll</HintPath>
		</Reference>
		<Reference Include="Il2CppFusion.Sockets">
			<HintPath>$(GamePath)/MelonLoader\Il2CppAssemblies\Il2CppFusion.Sockets.dll</HintPath>
		</Reference>
		<Reference Include="Il2CppFusion.Unity">
			<HintPath>$(GamePath)/MelonLoader\Il2CppAssemblies\Il2CppFusion.Unity.dll</HintPath>
		</Reference>
		<Reference Include="Il2CppGdkUtilities">
			<HintPath>$(GamePath)/MelonLoader\Il2CppAssemblies\Il2CppGdkUtilities.dll</HintPath>
		</Reference>
		<Reference Include="Il2CppGraphAndChart">
			<HintPath>$(GamePath)/MelonLoader\Il2CppAssemblies\Il2CppGraphAndChart.dll</HintPath>
		</Reference>
		<Reference Include="Il2CppLeTai.TranslucentImage">
			<HintPath>$(GamePath)/MelonLoader\Il2CppAssemblies\Il2CppLeTai.TranslucentImage.dll</HintPath>
		</Reference>
		<Reference Include="Il2CppLeTai.TranslucentImage.HDRP">
			<HintPath>$(GamePath)/MelonLoader\Il2CppAssemblies\Il2CppLeTai.TranslucentImage.HDRP.dll</HintPath>
		</Reference>
		<Reference Include="Il2CppMackySoft.SerializeReferenceExtensions">
			<HintPath>$(GamePath)/MelonLoader\Il2CppAssemblies\Il2CppMackySoft.SerializeReferenceExtensions.dll</HintPath>
		</Reference>
		<Reference Include="Il2Cppmcs">
			<HintPath>$(GamePath)/MelonLoader\Il2CppAssemblies\Il2Cppmcs.dll</HintPath>
		</Reference>
		<Reference Include="Il2CppMemoryPack.Core">
			<HintPath>$(GamePath)/MelonLoader\Il2CppAssemblies\Il2CppMemoryPack.Core.dll</HintPath>
		</Reference>
		<Reference Include="Il2CppMono.Security">
			<HintPath>$(GamePath)/MelonLoader\Il2CppAssemblies\Il2CppMono.Security.dll</HintPath>
		</Reference>
		<Reference Include="Il2Cppmscorlib">
			<HintPath>$(GamePath)/MelonLoader\Il2CppAssemblies\Il2Cppmscorlib.dll</HintPath>
		</Reference>
		<Reference Include="Il2CppNanoSockets">
			<HintPath>$(GamePath)/MelonLoader\Il2CppAssemblies\Il2CppNanoSockets.dll</HintPath>
		</Reference>
		<Reference Include="Il2CppNewtonsoft.Json">
			<HintPath>$(GamePath)/MelonLoader\Il2CppAssemblies\Il2CppNewtonsoft.Json.dll</HintPath>
		</Reference>
		<Reference Include="Il2CppPhoton3Unity3D">
			<HintPath>$(GamePath)/MelonLoader\Il2CppAssemblies\Il2CppPhoton3Unity3D.dll</HintPath>
		</Reference>
		<Reference Include="Il2CppQFSW.QC.Demo">
			<HintPath>$(GamePath)/MelonLoader\Il2CppAssemblies\Il2CppQFSW.QC.Demo.dll</HintPath>
		</Reference>
		<Reference Include="Il2CppQFSW.QC">
			<HintPath>$(GamePath)/MelonLoader\Il2CppAssemblies\Il2CppQFSW.QC.dll</HintPath>
		</Reference>
		<Reference Include="Il2CppQFSW.QC.Extras">
			<HintPath>$(GamePath)/MelonLoader\Il2CppAssemblies\Il2CppQFSW.QC.Extras.dll</HintPath>
		</Reference>
		<Reference Include="Il2CppQFSW.QC.Grammar">
			<HintPath>$(GamePath)/MelonLoader\Il2CppAssemblies\Il2CppQFSW.QC.Grammar.dll</HintPath>
		</Reference>
		<Reference Include="Il2CppQFSW.QC.Parsers">
			<HintPath>$(GamePath)/MelonLoader\Il2CppAssemblies\Il2CppQFSW.QC.Parsers.dll</HintPath>
		</Reference>
		<Reference Include="Il2CppQFSW.QC.ScanRules">
			<HintPath>$(GamePath)/MelonLoader\Il2CppAssemblies\Il2CppQFSW.QC.ScanRules.dll</HintPath>
		</Reference>
		<Reference Include="Il2CppQFSW.QC.Serializers">
			<HintPath>$(GamePath)/MelonLoader\Il2CppAssemblies\Il2CppQFSW.QC.Serializers.dll</HintPath>
		</Reference>
		<Reference Include="Il2CppQFSW.QC.Suggestors">
			<HintPath>$(GamePath)/MelonLoader\Il2CppAssemblies\Il2CppQFSW.QC.Suggestors.dll</HintPath>
		</Reference>
		<Reference Include="Il2CppQFSW.QC.UI">
			<HintPath>$(GamePath)/MelonLoader\Il2CppAssemblies\Il2CppQFSW.QC.UI.dll</HintPath>
		</Reference>
		<Reference Include="Il2CppRedAttributes">
			<HintPath>$(GamePath)/MelonLoader\Il2CppAssemblies\Il2CppRedAttributes.dll</HintPath>
		</Reference>
		<Reference Include="Il2CppRedEvents">
			<HintPath>$(GamePath)/MelonLoader\Il2CppAssemblies\Il2CppRedEvents.dll</HintPath>
		</Reference>
		<Reference Include="Il2CppRuntimeSceneGizmo.Runtime">
			<HintPath>$(GamePath)/MelonLoader\Il2CppAssemblies\Il2CppRuntimeSceneGizmo.Runtime.dll</HintPath>
		</Reference>
		<Reference Include="Il2CppSystem.Collections.Immutable">
			<HintPath>$(GamePath)/MelonLoader\Il2CppAssemblies\Il2CppSystem.Collections.Immutable.dll</HintPath>
		</Reference>
		<Reference Include="Il2CppSystem.Configuration">
			<HintPath>$(GamePath)/MelonLoader\Il2CppAssemblies\Il2CppSystem.Configuration.dll</HintPath>
		</Reference>
		<Reference Include="Il2CppSystem.Core">
			<HintPath>$(GamePath)/MelonLoader\Il2CppAssemblies\Il2CppSystem.Core.dll</HintPath>
		</Reference>
		<Reference Include="Il2CppSystem.Data">
			<HintPath>$(GamePath)/MelonLoader\Il2CppAssemblies\Il2CppSystem.Data.dll</HintPath>
		</Reference>
		<Reference Include="Il2CppSystem">
			<HintPath>$(GamePath)/MelonLoader\Il2CppAssemblies\Il2CppSystem.dll</HintPath>
		</Reference>
		<Reference Include="Il2CppSystem.Drawing">
			<HintPath>$(GamePath)/MelonLoader\Il2CppAssemblies\Il2CppSystem.Drawing.dll</HintPath>
		</Reference>
		<Reference Include="Il2CppSystem.IO.Compression">
			<HintPath>$(GamePath)/MelonLoader\Il2CppAssemblies\Il2CppSystem.IO.Compression.dll</HintPath>
		</Reference>
		<Reference Include="Il2CppSystem.Numerics">
			<HintPath>$(GamePath)/MelonLoader\Il2CppAssemblies\Il2CppSystem.Numerics.dll</HintPath>
		</Reference>
		<Reference Include="Il2CppSystem.Runtime.CompilerServices.Unsafe">
			<HintPath>$(GamePath)/MelonLoader\Il2CppAssemblies\Il2CppSystem.Runtime.CompilerServices.Unsafe.dll</HintPath>
		</Reference>
		<Reference Include="Il2CppSystem.Runtime.Serialization">
			<HintPath>$(GamePath)/MelonLoader\Il2CppAssemblies\Il2CppSystem.Runtime.Serialization.dll</HintPath>
		</Reference>
		<Reference Include="Il2CppSystem.Xml">
			<HintPath>$(GamePath)/MelonLoader\Il2CppAssemblies\Il2CppSystem.Xml.dll</HintPath>
		</Reference>
		<Reference Include="Il2CppSystem.Xml.Linq">
			<HintPath>$(GamePath)/MelonLoader\Il2CppAssemblies\Il2CppSystem.Xml.Linq.dll</HintPath>
		</Reference>
		<Reference Include="Il2CppTND.Upscaling.Framework.Runtime.Core">
			<HintPath>$(GamePath)/MelonLoader\Il2CppAssemblies\Il2CppTND.Upscaling.Framework.Runtime.Core.dll</HintPath>
		</Reference>
		<Reference Include="Il2CppTND.Upscaling.Framework.Runtime.HDRP">
			<HintPath>$(GamePath)/MelonLoader\Il2CppAssemblies\Il2CppTND.Upscaling.Framework.Runtime.HDRP.dll</HintPath>
		</Reference>
		<Reference Include="Il2CppTND.Upscaling.Framework.Runtime.Injectors">
			<HintPath>$(GamePath)/MelonLoader\Il2CppAssemblies\Il2CppTND.Upscaling.Framework.Runtime.Injectors.dll</HintPath>
		</Reference>
		<Reference Include="Il2CppTND.Upscaling.FSR3">
			<HintPath>$(GamePath)/MelonLoader\Il2CppAssemblies\Il2CppTND.Upscaling.FSR3.dll</HintPath>
		</Reference>
		<Reference Include="Il2CppTND.Upscaling.HDRP.DLSS">
			<HintPath>$(GamePath)/MelonLoader\Il2CppAssemblies\Il2CppTND.Upscaling.HDRP.DLSS.dll</HintPath>
		</Reference>
		<Reference Include="Il2CppTriInspector">
			<HintPath>$(GamePath)/MelonLoader\Il2CppAssemblies\Il2CppTriInspector.dll</HintPath>
		</Reference>
		<Reference Include="Il2CppUniTask.Addressables">
			<HintPath>$(GamePath)/MelonLoader\Il2CppAssemblies\Il2CppUniTask.Addressables.dll</HintPath>
		</Reference>
		<Reference Include="Il2CppUniTask">
			<HintPath>$(GamePath)/MelonLoader\Il2CppAssemblies\Il2CppUniTask.dll</HintPath>
		</Reference>
		<Reference Include="Il2CppXGamingRuntime">
			<HintPath>$(GamePath)/MelonLoader\Il2CppAssemblies\Il2CppXGamingRuntime.dll</HintPath>
		</Reference>
		<Reference Include="Il2CppZLinq">
			<HintPath>$(GamePath)/MelonLoader\Il2CppAssemblies\Il2CppZLinq.dll</HintPath>
		</Reference>
		<Reference Include="Il2CppZLinq.Unity">
			<HintPath>$(GamePath)/MelonLoader\Il2CppAssemblies\Il2CppZLinq.Unity.dll</HintPath>
		</Reference>
		<Reference Include="Il2CppZString">
			<HintPath>$(GamePath)/MelonLoader\Il2CppAssemblies\Il2CppZString.dll</HintPath>
		</Reference>
		<Reference Include="Il2Cpp__Generated">
			<HintPath>$(GamePath)/MelonLoader\Il2CppAssemblies\Il2Cpp__Generated.dll</HintPath>
		</Reference>
		<Reference Include="Unity.Addressables">
			<HintPath>$(GamePath)/MelonLoader\Il2CppAssemblies\Unity.Addressables.dll</HintPath>
		</Reference>
		<Reference Include="Unity.Burst">
			<HintPath>$(GamePath)/MelonLoader\Il2CppAssemblies\Unity.Burst.dll</HintPath>
		</Reference>
		<Reference Include="Unity.Burst.Unsafe">
			<HintPath>$(GamePath)/MelonLoader\Il2CppAssemblies\Unity.Burst.Unsafe.dll</HintPath>
		</Reference>
		<Reference Include="Unity.Cinemachine">
			<HintPath>$(GamePath)/MelonLoader\Il2CppAssemblies\Unity.Cinemachine.dll</HintPath>
		</Reference>
		<Reference Include="Unity.Collections">
			<HintPath>$(GamePath)/MelonLoader\Il2CppAssemblies\Unity.Collections.dll</HintPath>
		</Reference>
		<Reference Include="Unity.Collections.LowLevel.ILSupport">
			<HintPath>$(GamePath)/MelonLoader\Il2CppAssemblies\Unity.Collections.LowLevel.ILSupport.dll</HintPath>
		</Reference>
		<Reference Include="Unity.InputSystem">
			<HintPath>$(GamePath)/MelonLoader\Il2CppAssemblies\Unity.InputSystem.dll</HintPath>
		</Reference>
		<Reference Include="Unity.InputSystem.ForUI">
			<HintPath>$(GamePath)/MelonLoader\Il2CppAssemblies\Unity.InputSystem.ForUI.dll</HintPath>
		</Reference>
		<Reference Include="Unity.InternalAPIEngineBridge.004">
			<HintPath>$(GamePath)/MelonLoader\Il2CppAssemblies\Unity.InternalAPIEngineBridge.004.dll</HintPath>
		</Reference>
		<Reference Include="Unity.Mathematics">
			<HintPath>$(GamePath)/MelonLoader\Il2CppAssemblies\Unity.Mathematics.dll</HintPath>
		</Reference>
		<Reference Include="Unity.MemoryProfiler">
			<HintPath>$(GamePath)/MelonLoader\Il2CppAssemblies\Unity.MemoryProfiler.dll</HintPath>
		</Reference>
		<Reference Include="Unity.RenderPipelines.Core.Runtime">
			<HintPath>$(GamePath)/MelonLoader\Il2CppAssemblies\Unity.RenderPipelines.Core.Runtime.dll</HintPath>
		</Reference>
		<Reference Include="Unity.RenderPipelines.Core.Samples.Runtime">
			<HintPath>$(GamePath)/MelonLoader\Il2CppAssemblies\Unity.RenderPipelines.Core.Samples.Runtime.dll</HintPath>
		</Reference>
		<Reference Include="Unity.RenderPipelines.GPUDriven.Runtime">
			<HintPath>$(GamePath)/MelonLoader\Il2CppAssemblies\Unity.RenderPipelines.GPUDriven.Runtime.dll</HintPath>
		</Reference>
		<Reference Include="Unity.RenderPipelines.HighDefinition.Config.Runtime">
			<HintPath>$(GamePath)/MelonLoader\Il2CppAssemblies\Unity.RenderPipelines.HighDefinition.Config.Runtime.dll</HintPath>
		</Reference>
		<Reference Include="Unity.RenderPipelines.HighDefinition.Runtime">
			<HintPath>$(GamePath)/MelonLoader\Il2CppAssemblies\Unity.RenderPipelines.HighDefinition.Runtime.dll</HintPath>
		</Reference>
		<Reference Include="Unity.RenderPipelines.HighDefinition.Samples.Common.Runtime">
			<HintPath>$(GamePath)/MelonLoader\Il2CppAssemblies\Unity.RenderPipelines.HighDefinition.Samples.Common.Runtime.dll</HintPath>
		</Reference>
		<Reference Include="Unity.ResourceManager">
			<HintPath>$(GamePath)/MelonLoader\Il2CppAssemblies\Unity.ResourceManager.dll</HintPath>
		</Reference>
		<Reference Include="Unity.Splines">
			<HintPath>$(GamePath)/MelonLoader\Il2CppAssemblies\Unity.Splines.dll</HintPath>
		</Reference>
		<Reference Include="Unity.TextMeshPro">
			<HintPath>$(GamePath)/MelonLoader\Il2CppAssemblies\Unity.TextMeshPro.dll</HintPath>
		</Reference>
		<Reference Include="Unity.Timeline">
			<HintPath>$(GamePath)/MelonLoader\Il2CppAssemblies\Unity.Timeline.dll</HintPath>
		</Reference>
		<Reference Include="Unity.UnifiedRayTracing.Runtime">
			<HintPath>$(GamePath)/MelonLoader\Il2CppAssemblies\Unity.UnifiedRayTracing.Runtime.dll</HintPath>
		</Reference>
		<Reference Include="Unity.VisualEffectGraph.Runtime">
			<HintPath>$(GamePath)/MelonLoader\Il2CppAssemblies\Unity.VisualEffectGraph.Runtime.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.AccessibilityModule">
			<HintPath>$(GamePath)/MelonLoader\Il2CppAssemblies\UnityEngine.AccessibilityModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.AdaptivePerformanceModule">
			<HintPath>$(GamePath)/MelonLoader\Il2CppAssemblies\UnityEngine.AdaptivePerformanceModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.AIModule">
			<HintPath>$(GamePath)/MelonLoader\Il2CppAssemblies\UnityEngine.AIModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.AMDModule">
			<HintPath>$(GamePath)/MelonLoader\Il2CppAssemblies\UnityEngine.AMDModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.AndroidJNIModule">
			<HintPath>$(GamePath)/MelonLoader\Il2CppAssemblies\UnityEngine.AndroidJNIModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.AnimationModule">
			<HintPath>$(GamePath)/MelonLoader\Il2CppAssemblies\UnityEngine.AnimationModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.ARModule">
			<HintPath>$(GamePath)/MelonLoader\Il2CppAssemblies\UnityEngine.ARModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.AssetBundleModule">
			<HintPath>$(GamePath)/MelonLoader\Il2CppAssemblies\UnityEngine.AssetBundleModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.AudioModule">
			<HintPath>$(GamePath)/MelonLoader\Il2CppAssemblies\UnityEngine.AudioModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.ClothModule">
			<HintPath>$(GamePath)/MelonLoader\Il2CppAssemblies\UnityEngine.ClothModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.ContentLoadModule">
			<HintPath>$(GamePath)/MelonLoader\Il2CppAssemblies\UnityEngine.ContentLoadModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.CoreModule">
			<HintPath>$(GamePath)/MelonLoader\Il2CppAssemblies\UnityEngine.CoreModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.CrashReportingModule">
			<HintPath>$(GamePath)/MelonLoader\Il2CppAssemblies\UnityEngine.CrashReportingModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.DirectorModule">
			<HintPath>$(GamePath)/MelonLoader\Il2CppAssemblies\UnityEngine.DirectorModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine">
			<HintPath>$(GamePath)/MelonLoader\Il2CppAssemblies\UnityEngine.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.DSPGraphModule">
			<HintPath>$(GamePath)/MelonLoader\Il2CppAssemblies\UnityEngine.DSPGraphModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.GameCenterModule">
			<HintPath>$(GamePath)/MelonLoader\Il2CppAssemblies\UnityEngine.GameCenterModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.GIModule">
			<HintPath>$(GamePath)/MelonLoader\Il2CppAssemblies\UnityEngine.GIModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.GraphicsStateCollectionSerializerModule">
			<HintPath>$(GamePath)/MelonLoader\Il2CppAssemblies\UnityEngine.GraphicsStateCollectionSerializerModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.GridModule">
			<HintPath>$(GamePath)/MelonLoader\Il2CppAssemblies\UnityEngine.GridModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.HierarchyCoreModule">
			<HintPath>$(GamePath)/MelonLoader\Il2CppAssemblies\UnityEngine.HierarchyCoreModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.HierarchyModule">
			<HintPath>$(GamePath)/MelonLoader\Il2CppAssemblies\UnityEngine.HierarchyModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.HotReloadModule">
			<HintPath>$(GamePath)/MelonLoader\Il2CppAssemblies\UnityEngine.HotReloadModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.IdentifiersModule">
			<HintPath>$(GamePath)/MelonLoader\Il2CppAssemblies\UnityEngine.IdentifiersModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.ImageConversionModule">
			<HintPath>$(GamePath)/MelonLoader\Il2CppAssemblies\UnityEngine.ImageConversionModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.IMGUIModule">
			<HintPath>$(GamePath)/MelonLoader\Il2CppAssemblies\UnityEngine.IMGUIModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.InputForUIModule">
			<HintPath>$(GamePath)/MelonLoader\Il2CppAssemblies\UnityEngine.InputForUIModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.InputLegacyModule">
			<HintPath>$(GamePath)/MelonLoader\Il2CppAssemblies\UnityEngine.InputLegacyModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.InputModule">
			<HintPath>$(GamePath)/MelonLoader\Il2CppAssemblies\UnityEngine.InputModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.InsightsModule">
			<HintPath>$(GamePath)/MelonLoader\Il2CppAssemblies\UnityEngine.InsightsModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.JSONSerializeModule">
			<HintPath>$(GamePath)/MelonLoader\Il2CppAssemblies\UnityEngine.JSONSerializeModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.LocalizationModule">
			<HintPath>$(GamePath)/MelonLoader\Il2CppAssemblies\UnityEngine.LocalizationModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.MarshallingModule">
			<HintPath>$(GamePath)/MelonLoader\Il2CppAssemblies\UnityEngine.MarshallingModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.MultiplayerModule">
			<HintPath>$(GamePath)/MelonLoader\Il2CppAssemblies\UnityEngine.MultiplayerModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.NVIDIAModule">
			<HintPath>$(GamePath)/MelonLoader\Il2CppAssemblies\UnityEngine.NVIDIAModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.ParticleSystemModule">
			<HintPath>$(GamePath)/MelonLoader\Il2CppAssemblies\UnityEngine.ParticleSystemModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.PerformanceReportingModule">
			<HintPath>$(GamePath)/MelonLoader\Il2CppAssemblies\UnityEngine.PerformanceReportingModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.Physics2DModule">
			<HintPath>$(GamePath)/MelonLoader\Il2CppAssemblies\UnityEngine.Physics2DModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.PhysicsBackendPhysXModule">
			<HintPath>$(GamePath)/MelonLoader\Il2CppAssemblies\UnityEngine.PhysicsBackendPhysXModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.PhysicsModule">
			<HintPath>$(GamePath)/MelonLoader\Il2CppAssemblies\UnityEngine.PhysicsModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.PropertiesModule">
			<HintPath>$(GamePath)/MelonLoader\Il2CppAssemblies\UnityEngine.PropertiesModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.RenderAs2DModule">
			<HintPath>$(GamePath)/MelonLoader\Il2CppAssemblies\UnityEngine.RenderAs2DModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.RuntimeInitializeOnLoadManagerInitializerModule">
			<HintPath>$(GamePath)/MelonLoader\Il2CppAssemblies\UnityEngine.RuntimeInitializeOnLoadManagerInitializerModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.ScreenCaptureModule">
			<HintPath>$(GamePath)/MelonLoader\Il2CppAssemblies\UnityEngine.ScreenCaptureModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.ShaderRuntimeModule">
			<HintPath>$(GamePath)/MelonLoader\Il2CppAssemblies\UnityEngine.ShaderRuntimeModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.ShaderVariantAnalyticsModule">
			<HintPath>$(GamePath)/MelonLoader\Il2CppAssemblies\UnityEngine.ShaderVariantAnalyticsModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.SharedInternalsModule">
			<HintPath>$(GamePath)/MelonLoader\Il2CppAssemblies\UnityEngine.SharedInternalsModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.SpriteMaskModule">
			<HintPath>$(GamePath)/MelonLoader\Il2CppAssemblies\UnityEngine.SpriteMaskModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.SpriteShapeModule">
			<HintPath>$(GamePath)/MelonLoader\Il2CppAssemblies\UnityEngine.SpriteShapeModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.StreamingModule">
			<HintPath>$(GamePath)/MelonLoader\Il2CppAssemblies\UnityEngine.StreamingModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.SubstanceModule">
			<HintPath>$(GamePath)/MelonLoader\Il2CppAssemblies\UnityEngine.SubstanceModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.SubsystemsModule">
			<HintPath>$(GamePath)/MelonLoader\Il2CppAssemblies\UnityEngine.SubsystemsModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.TerrainModule">
			<HintPath>$(GamePath)/MelonLoader\Il2CppAssemblies\UnityEngine.TerrainModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.TerrainPhysicsModule">
			<HintPath>$(GamePath)/MelonLoader\Il2CppAssemblies\UnityEngine.TerrainPhysicsModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.TextCoreFontEngineModule">
			<HintPath>$(GamePath)/MelonLoader\Il2CppAssemblies\UnityEngine.TextCoreFontEngineModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.TextCoreTextEngineModule">
			<HintPath>$(GamePath)/MelonLoader\Il2CppAssemblies\UnityEngine.TextCoreTextEngineModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.TextRenderingModule">
			<HintPath>$(GamePath)/MelonLoader\Il2CppAssemblies\UnityEngine.TextRenderingModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.TilemapModule">
			<HintPath>$(GamePath)/MelonLoader\Il2CppAssemblies\UnityEngine.TilemapModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.TLSModule">
			<HintPath>$(GamePath)/MelonLoader\Il2CppAssemblies\UnityEngine.TLSModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.UI">
			<HintPath>$(GamePath)/MelonLoader\Il2CppAssemblies\UnityEngine.UI.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.UIElementsModule">
			<HintPath>$(GamePath)/MelonLoader\Il2CppAssemblies\UnityEngine.UIElementsModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.UIModule">
			<HintPath>$(GamePath)/MelonLoader\Il2CppAssemblies\UnityEngine.UIModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.UmbraModule">
			<HintPath>$(GamePath)/MelonLoader\Il2CppAssemblies\UnityEngine.UmbraModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.UnityAnalyticsCommonModule">
			<HintPath>$(GamePath)/MelonLoader\Il2CppAssemblies\UnityEngine.UnityAnalyticsCommonModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.UnityAnalyticsModule">
			<HintPath>$(GamePath)/MelonLoader\Il2CppAssemblies\UnityEngine.UnityAnalyticsModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.UnityConnectModule">
			<HintPath>$(GamePath)/MelonLoader\Il2CppAssemblies\UnityEngine.UnityConnectModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.UnityConsentModule">
			<HintPath>$(GamePath)/MelonLoader\Il2CppAssemblies\UnityEngine.UnityConsentModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.UnityCurlModule">
			<HintPath>$(GamePath)/MelonLoader\Il2CppAssemblies\UnityEngine.UnityCurlModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.UnityWebRequestAssetBundleModule">
			<HintPath>$(GamePath)/MelonLoader\Il2CppAssemblies\UnityEngine.UnityWebRequestAssetBundleModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.UnityWebRequestAudioModule">
			<HintPath>$(GamePath)/MelonLoader\Il2CppAssemblies\UnityEngine.UnityWebRequestAudioModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.UnityWebRequestModule">
			<HintPath>$(GamePath)/MelonLoader\Il2CppAssemblies\UnityEngine.UnityWebRequestModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.UnityWebRequestTextureModule">
			<HintPath>$(GamePath)/MelonLoader\Il2CppAssemblies\UnityEngine.UnityWebRequestTextureModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.UnityWebRequestWWWModule">
			<HintPath>$(GamePath)/MelonLoader\Il2CppAssemblies\UnityEngine.UnityWebRequestWWWModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.VectorGraphicsModule">
			<HintPath>$(GamePath)/MelonLoader\Il2CppAssemblies\UnityEngine.VectorGraphicsModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.VehiclesModule">
			<HintPath>$(GamePath)/MelonLoader\Il2CppAssemblies\UnityEngine.VehiclesModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.VFXModule">
			<HintPath>$(GamePath)/MelonLoader\Il2CppAssemblies\UnityEngine.VFXModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.VideoModule">
			<HintPath>$(GamePath)/MelonLoader\Il2CppAssemblies\UnityEngine.VideoModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.VRModule">
			<HintPath>$(GamePath)/MelonLoader\Il2CppAssemblies\UnityEngine.VRModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.WindModule">
			<HintPath>$(GamePath)/MelonLoader\Il2CppAssemblies\UnityEngine.WindModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.XRModule">
			<HintPath>$(GamePath)/MelonLoader\Il2CppAssemblies\UnityEngine.XRModule.dll</HintPath>
		</Reference>
		<Reference Include="MelonLoader">
			<HintPath>$(GamePath)/MelonLoader\net6\MelonLoader.dll</HintPath>
		</Reference>
		<Reference Include="0Harmony">
			<HintPath>$(GamePath)/MelonLoader\net6\0Harmony.dll</HintPath>
		</Reference>
		<Reference Include="Il2CppInterop.Runtime">
			<HintPath>$(GamePath)/MelonLoader\net6\Il2CppInterop.Runtime.dll</HintPath>
		</Reference>
		<Reference Include="Il2CppInterop.Common">
			<HintPath>$(GamePath)/MelonLoader\net6\Il2CppInterop.Common.dll</HintPath>
		</Reference>

	</ItemGroup>

	<PropertyGroup>
		<AllowUnsafeBlocks>True</AllowUnsafeBlocks>
		<EnableDefaultCompileItems>false</EnableDefaultCompileItems>
	</PropertyGroup>

	<ItemGroup>
		<Compile Include="Core.cs" />
		<Content Include="Directory.Build.props" />
	</ItemGroup>
	
	<Target Name="PostBuild" AfterTargets="PostBuildEvent">
		<Exec Command="COPY &quot;$(TargetPath)&quot; &quot;$(GamePath)/Mods&quot;" />
	</Target>
</Project>